-- Burger King
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '61 Broadway', 'MALDEN', '', '02148', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday": "6am - 10pm", "tuesday": "6am - 10pm", "wednesday": "6am - 10pm", "thursday": "6am - 10pm", "friday": "6am - 10pm", "saturday": "6am - 10pm", "sunday": "6am - 10pm"}'::jsonb, '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}'::jsonb);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '150 Everett Avenue', 'Chelsea', '', '02150', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday": "6am - 11pm", "tuesday": "6am - 11pm", "wednesday": "6am - 11pm", "thursday": "6am - 11pm", "friday": "6am - 11pm", "saturday": "6am - 11pm", "sunday": "6am - 11pm"}'::jsonb, '{"monday": "6am - 12am", "tuesday": "6am - 12am", "wednesday": "6am - 12am", "thursday": "6am - 12am", "friday": "6am - 12am", "saturday": "6am - 12am", "sunday": "6am - 12am"}'::jsonb);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '383 Mystic Avenue', 'MEDFORD', '', '02155', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday": "6am - 10pm", "tuesday": "6am - 10pm", "wednesday": "6am - 10pm", "thursday": "6am - 10pm", "friday": "6am - 10pm", "saturday": "6am - 10pm", "sunday": "6am - 10pm"}'::jsonb, '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}'::jsonb);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '679 Concord Avenue', 'CAMBRIDGE', '', '02138', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday": "5:30am - 10pm", "tuesday": "5:30am - 10pm", "wednesday": "5:30am - 10pm", "thursday": "5:30am - 10pm", "friday": "5:30am - 10pm", "saturday": "5:30am - 10pm", "sunday": "5:30am - 10pm"}'::jsonb, '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}'::jsonb);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '210 Brighton Avenue', 'ALLSTON', '', '02134', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday": "6am - 10pm", "tuesday": "6am - 9pm", "wednesday": "6am - 10pm", "thursday": "6am - 10pm", "friday": "6am - 10pm", "saturday": "6am - 10pm", "sunday": "6am - 10pm"}'::jsonb, '{"monday": "6am - 1am", "tuesday": "6am - 9pm", "wednesday": "6am - 1am", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}'::jsonb);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', 'Burger King Location', NULL, NULL, NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '185 Somerville Avenue', 'SOMERVILLE', '', '02143', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday": "6am - 11pm", "tuesday": "6am - 11pm", "wednesday": "6am - 11pm", "thursday": "6am - 11pm", "friday": "6am - 11pm", "saturday": "6am - 11pm", "sunday": "6am - 11pm"}'::jsonb, '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}'::jsonb);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '1208 Dorchester Avenue', 'DORCHESTER', '', '02125', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday": "6am - 11pm", "tuesday": "6am - 11pm", "wednesday": "6am - 11pm", "thursday": "6am - 11pm", "friday": "6am - 11pm", "saturday": "6am - 11pm", "sunday": "6am - 11pm"}'::jsonb, '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}'::jsonb);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '128 Tremont Street', 'BOSTON', '', '02108', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday": "7am - 11pm", "tuesday": "7am - 11pm", "wednesday": "7am - 11pm", "thursday": "7am - 11pm", "friday": "7am - 11pm", "saturday": "7am - 11pm", "sunday": "7am - 11pm"}'::jsonb, NULL);
INSERT INTO restaurant_locations (name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours) VALUES ('Burger King', 'Burger King', '1 Maverick Square', 'BOSTON', '', '02128', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday": "7am - 10pm", "tuesday": "7am - 10pm", "wednesday": "7am - 10pm", "thursday": "7am - 10pm", "friday": "7am - 10pm", "saturday": "7am - 10pm", "sunday": "7am - 10pm"}'::jsonb, NULL);


-- Chick-fil-A's
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chick-fil-A', 'Chick-fil-A', '569 Boylston St', 'Boston', 'MA', '02116', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6:30am - 11pm","tuesday":"6:30am - 11pm","wednesday":"6:30am - 11pm","thursday":"6:30am - 11pm","friday":"6:30am - 11pm","saturday":"6:30am - 11pm","sunday":"Closed"}'::jsonb, '{}'::jsonb ); 
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chick-fil-A', 'Chick-fil-A', '140 Providence Hwy', 'Dedham', 'MA', '02026', NULL, NULL, TRUE, TRUE, TRUE, TRUE, '{"monday":"6:30am - 10pm","tuesday":"6:30am - 10pm","wednesday":"6:30am - 10pm","thursday":"6:30am - 10pm","friday":"6:30am - 10pm","saturday":"6:30am - 10pm","sunday":"Closed"}'::jsonb, '{"monday":"6:30am - 10pm","tuesday":"6:30am - 10pm","wednesday":"6:30am - 10pm","thursday":"6:30am - 10pm","friday":"6:30am - 10pm","saturday":"6:30am - 10pm","sunday":"Closed"}'::jsonb );

-- Wendy's
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Wendy''s', 'Wendy''s', '157 Massachusetts Avenue', 'Boston', 'MA', '02127', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"8am - 12am","tuesday":"8am - 12am","wednesday":"8am - 12am","thursday":"8am - 12am","friday":"8am - 12am","saturday":"8am - 12am","sunday":"8am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Wendy''s', 'Wendy''s', '71 Summer Street', 'Boston', 'MA', '02110', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"7am - 11pm","tuesday":"7am - 11pm","wednesday":"7am - 11pm","thursday":"7am - 11pm","friday":"7am - 11pm","saturday":"8am - 11pm","sunday":"8am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Wendy''s', 'Wendy''s', '1724 Revere Beach Parkway', 'Everett', 'MA', '02149', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday":"6am - 2am","tuesday":"6am - 2am","wednesday":"6am - 2am","thursday":"6am - 2am","friday":"6am - 2am","saturday":"6am - 2am","sunday":"6am - 2am"}'::jsonb, '{"monday":"6am - 2am","tuesday":"6am - 2am","wednesday":"6am - 2am","thursday":"6am - 2am","friday":"6am - 2am","saturday":"6am - 2am","sunday":"6am - 2am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Wendy''s', 'Wendy''s', '330 Middlesex Ave', 'Medford', 'MA', '02155', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 2am","tuesday":"6am - 2am","wednesday":"6am - 2am","thursday":"6am-3am","friday":"6am-3am","saturday":"6am-3am","sunday":"6am - 2am"}'::jsonb, '{"monday":"6am - 2am","tuesday":"6am - 2am","wednesday":"6am - 2am","thursday":"6am-3am","friday":"6am-3am","saturday":"6am-3am","sunday":"6am - 2am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Wendy''s', 'Wendy''s', '191 Newport Ave', 'Quincy', 'MA', '02170', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 2am","tuesday":"6am - 2am","wednesday":"6am - 2am","thursday":"6am - 2am","friday":"6am-3am","saturday":"6am-3am","sunday":"6am - 2am"}'::jsonb, '{"monday":"6am - 2am","tuesday":"6am - 2am","wednesday":"6am - 2am","thursday":"6am - 2am","friday":"6am-3am","saturday":"6am-3am","sunday":"6am - 2am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Wendy''s', 'Wendy''s', '520 Southern Artery', 'Quincy', 'MA', '02169', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"630am - 4am","tuesday":"630am - 4am","wednesday":"630am - 4am","thursday":"630am - 4am","friday":"630am - 4am","saturday":"630am - 4am","sunday":"630am - 4am"}'::jsonb, '{"monday":"630am - 4am","tuesday":"630am - 4am","wednesday":"630am - 4am","thursday":"630am - 4am","friday":"630am - 4am","saturday":"630am - 4am","sunday":"630am - 4am"}'::jsonb );

-- Taco Bell
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Taco Bell', 'Taco Bell', '1683 Revere Beach Pkwy', 'Everett', 'MA', '02149', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday":"7am-3am","tuesday":"7am-330am","wednesday":"7am-4am","thursday":"530am-529am","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"530am - 330am"}'::jsonb, '{"monday":"7am - 3am","tuesday":"7am - 330am","wednesday":"7am - 4am","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"530am - 330am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Taco Bell', 'Taco Bell', '1560 VFW Pkwy', 'West Roxbury', 'MA', '02132', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday":"9am - 2am","tuesday":"9am - 2am","wednesday":"9am - 2am","thursday":"9am - 2am","friday":"9am - 2am","saturday":"9am - 2am","sunday":"9am - 2am"}'::jsonb, '{"monday":"9am - 2am","tuesday":"9am - 2am","wednesday":"9am - 2am","thursday":"9am - 2am","friday":"9am - 2am","saturday":"9am - 2am","sunday":"9am - 2am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Taco Bell', 'Taco Bell', '707 Hancock St', 'Quincy', 'MA', '02170', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday":"10am - 2am","tuesday":"10am - 2am","wednesday":"10am - 2am","thursday":"10am - 2am","friday":"10am - 2am","saturday":"10am - 2am","sunday":"10am - 2am"}'::jsonb, '{"monday":"10am - 2am","tuesday":"10am - 2am","wednesday":"10am - 2am","thursday":"10am - 2am","friday":"10am - 2am","saturday":"10am - 2am","sunday":"10am - 2am"}'::jsonb );

-- Chipotle
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '176 Providence Hwy', 'Dedham', 'MA', '02026', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '60 Newport Ave', 'Quincy', 'MA', '02171', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '27 District Ave', 'Dorchester', 'MA', '02125', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '1924 Beacon St', 'Brighton', 'MA', '02135', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '876 Commonwealth Avenue', 'Brookline', 'MA', '02215', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '148 Brookline Ave', 'Boston', 'MA', '02215', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '553 Boylston St', 'Boston', 'MA', '02116', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '8 Park Plz', 'Boston', 'MA', '02116', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '101 Summer St', 'Boston', 'MA', '02110', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"10am - 10pm","tuesday":"10am - 10pm","wednesday":"10am - 10pm","thursday":"10am - 10pm","friday":"10am - 10pm","saturday":"10am - 10pm","sunday":"10am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '51 Boston Wharf Rd', 'Boston', 'MA', '02210', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '255 Main St', 'Cambridge', 'MA', '02142', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am - 11pm","saturday":"10am - 11pm","sunday":"10am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '598 Massachusetts Ave', 'Cambridge', 'MA', '02139', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '274 Elm St', 'Somerville', 'MA', '02144', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '616 Fellsway', 'Medford', 'MA', '02155', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Chipotle', 'Chipotle', '227 Alewife Brook Pkwy', 'Cambridge', 'MA', '02138', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"1045am - 11pm","tuesday":"1045am - 11pm","wednesday":"1045am - 11pm","thursday":"1045am - 11pm","friday":"1045am - 11pm","saturday":"1045am - 11pm","sunday":"1045am - 11pm"}'::jsonb, '{}'::jsonb );

-- KFC
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'KFC', 'KFC', '75 Broadway', 'Malden', 'MA', '02148', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday":"10am - 10pm","tuesday":"10am - 10pm","wednesday":"10am - 10pm","thursday":"10am - 10pm","friday":"10am - 11pm","saturday":"10am - 11pm","sunday":"10am - 10pm"}'::jsonb, '{"monday":"10am - 10pm","tuesday":"10am - 10pm","wednesday":"10am - 10pm","thursday":"10am - 10pm","friday":"10am - 11pm","saturday":"10am - 11pm","sunday":"10am - 10pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'KFC', 'KFC', '695 Columbia Rd', 'Dorchester', 'MA', '02125', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am - 11pm","saturday":"10am - 11pm","sunday":"10am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'KFC', 'KFC', '465 Washington St', 'Dorchester', 'MA', '02124', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am - 12am","saturday":"10am - 12am","sunday":"10am - 11pm"}'::jsonb, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am - 12am","saturday":"10am - 12am","sunday":"10am - 11pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'KFC', 'KFC', '20 Everett Avenue', 'Everett', 'MA', '02149', NULL, NULL, TRUE, TRUE, TRUE, TRUE, '{"monday":"1030am - 11pm","tuesday":"1030am - 11pm","wednesday":"1030am - 11pm","thursday":"1030am - 11pm","friday":"1030am - 11pm","saturday":"1030am - 11pm","sunday":"1030am - 11pm"}'::jsonb, '{"monday":"1030am - 11pm","tuesday":"1030am - 11pm","wednesday":"1030am - 11pm","thursday":"1030am - 11pm","friday":"1030am - 11pm","saturday":"1030am - 11pm","sunday":"1030am - 11pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'KFC', 'KFC', '30 N. Beacon Street', 'Allston', 'MA', '02134', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am - 11pm","saturday":"10am - 11pm","sunday":"10am - 11pm"}'::jsonb, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am - 11pm","saturday":"10am - 11pm","sunday":"10am - 11pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'KFC', 'KFC', '625 American Legion Hwy', 'Roslindale', 'MA', '02131', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am-12am","saturday":"10am-12am","sunday":"10am - 11pm"}'::jsonb, '{"monday":"10am - 11pm","tuesday":"10am - 11pm","wednesday":"10am - 11pm","thursday":"10am - 11pm","friday":"10am-12am","saturday":"10am-12am","sunday":"10am - 11pm"}'::jsonb );

-- Popeyes
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Popeyes', 'Popeyes', '502 Southern Artery', 'Quincy', 'MA', '02169', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday":"1030am - 1030pm","tuesday":"1030am - 1030pm","wednesday":"1030am - 1030pm","thursday":"1030am - 1030pm","friday":"1030am - 1030pm","saturday":"1030am - 1030pm","sunday":"1030am - 1030pm"}'::jsonb, '{"monday":"1030am - 11pm","tuesday":"1030am - 11pm","wednesday":"1030am - 11pm","thursday":"1030am - 11pm","friday":"1030am - 12am","saturday":"1030am - 12am","sunday":"1030am - 11pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Popeyes', 'Popeyes', '330 Martin Luther King Blvd', 'Roxbury', 'MA', '02119', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"10am - 12am","tuesday":"10am - 12am","wednesday":"10am - 12am","thursday":"10am - 12am","friday":"10am - 1am","saturday":"10am - 1am","sunday":"10am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Popeyes', 'Popeyes', '1630 VFW Parkway', 'West Roxbury', 'MA', '02132', NULL, NULL, TRUE, FALSE, TRUE, FALSE, '{"monday":"1030am -  10pm","tuesday":"1030am -  10pm","wednesday":"1030am -  10pm","thursday":"1030am -  10pm","friday":"1030am -  10pm","saturday":"1030am -  10pm","sunday":"1030am -  10pm"}'::jsonb, '{"monday":"1030am - 11pm","tuesday":"1030am - 11pm","wednesday":"1030am - 11pm","thursday":"1030am - 11pm","friday":"1030am - 12am","saturday":"1030am - 12am","sunday":"1030am - 11pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Popeyes', 'Popeyes', '275 Centre St', 'Newton', 'MA', '02458', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"1030am - 12am","tuesday":"1030am - 12am","wednesday":"1030am - 12am","thursday":"1030am - 12am","friday":"1030am - 1am","saturday":"1030am - 1am","sunday":"1030am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Popeyes', 'Popeyes', '710 American Legion hwy', 'Roslindale', 'MA', '02131', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"10am - 12am","tuesday":"10am - 12am","wednesday":"10am - 12am","thursday":"10am - 12am","friday":"10am - 12am","saturday":"10am - 12am","sunday":"10am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Popeyes', 'Popeyes', '360 Huntington Ave', 'Boston', 'MA', '02115', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"11am - 5pm","tuesday":"11am - 5pm","wednesday":"11am - 5pm","thursday":"11am - 5pm","friday":"11am - 3pm","saturday":"Closed","sunday":"Closed"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Popeyes', 'Popeyes', '1886 Revere Beach Pkwy', 'Everett', 'MA', '02149', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"10am - 12am","tuesday":"10am - 12am","wednesday":"10am - 12am","thursday":"10am - 12am","friday":"10am - 1am","saturday":"10am - 1am","sunday":"10am - 12am"}'::jsonb, '{}'::jsonb );


-- Jersey Mike's
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Jersey Mike''s', 'Jersey Mike''s', '70 Staniford Street', 'Boston', 'MA', '02114', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"10am - 9pm","tuesday":"10am - 9pm","wednesday":"10am - 9pm","thursday":"10am - 9pm","friday":"10am - 10pm","saturday":"10am - 10pm","sunday":"10am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Jersey Mike''s', 'Jersey Mike''s', '108 Bond Square', 'Watertown', 'MA', '02472', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"10am - 9pm","tuesday":"10am - 9pm","wednesday":"10am - 9pm","thursday":"10am - 9pm","friday":"10am - 9pm","saturday":"10am - 9pm","sunday":"10am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Jersey Mike''s', 'Jersey Mike''s', '466 B Washington Street', 'Brighton', 'MA', '02135', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"9am - 9pm","tuesday":"9am - 9pm","wednesday":"9am - 9pm","thursday":"9am - 9pm","friday":"9am - 9pm","saturday":"9am - 9pm","sunday":"9am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Jersey Mike''s', 'Jersey Mike''s', '395 Providence Highway', 'Dedham', 'MA', '02026', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"10am - 9pm","tuesday":"10am - 9pm","wednesday":"10am - 9pm","thursday":"10am - 9pm","friday":"10am - 9pm","saturday":"10am - 9pm","sunday":"10am - 9pm"}'::jsonb, '{}'::jsonb );

-- Shake Shack
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '1 Broadway', 'Everett', 'MA', '02149', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"11am - 1am","tuesday":"11am - 1am","wednesday":"11am - 1am","thursday":"11am - 1am","friday":"11am - 330am","saturday":"11am - 330am","sunday":"11am - 1am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '355 Assembly Row', 'Somerville', 'MA', '02145', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"1030am - 11pm","tuesday":"1030am - 11pm","wednesday":"1030am - 11pm","thursday":"1030am - 11pm","friday":"1030am - 1130pm","saturday":"1030am - 1130pm","sunday":"1030am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '92 Winthrop Street', 'Cambridge', 'MA', '02138', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"11am - 10pm","tuesday":"11am - 10pm","wednesday":"11am - 10pm","thursday":"11am - 11pm","friday":"11am - 11pm","saturday":"11am - 11pm","sunday":"11am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '322 Washington Street', 'Boston', 'MA', '02108', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"1030am - 930pm","tuesday":"1030am - 930pm","wednesday":"1030am - 930pm","thursday":"1030am - 930pm","friday":"1030am - 1030pm","saturday":"1030am - 1030pm","sunday":"1030am - 930pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '77 Seaport Blvd', 'Boston', 'MA', '02210', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"10am - 1030pm","tuesday":"10am - 1030pm","wednesday":"10am - 1030pm","thursday":"10am - 1030pm","friday":"10am - 1030pm","saturday":"10am - 1030pm","sunday":"10am - 1030pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '234-236 Newbury St', 'Boston', 'MA', '02116', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"1030am - 1130pm","tuesday":"1030am - 1130pm","wednesday":"1030am - 1130pm","thursday":"1030am - 1130pm","friday":"1030am - 1130pm","saturday":"1030am - 1130pm","sunday":"1030am - 1130pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '800 Boylston Street', 'Boston', 'MA', '02199', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"11am - 9pm","tuesday":"11am - 9pm","wednesday":"11am - 9pm","thursday":"11am - 9pm","friday":"1030am - 930pm","saturday":"1030am - 930pm","sunday":"1030am - 8pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Shake Shack', 'Shake Shack', '49 Boylston St #4900', 'Chestnut Hill', 'MA', '02467', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"1030am - 10pm","tuesday":"1030am - 10pm","wednesday":"1030am - 10pm","thursday":"1030am - 11pm","friday":"1030am - 11pm","saturday":"1030am - 11pm","sunday":"1030am - 10pm"}'::jsonb, '{}'::jsonb );

-- Panera
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '5 White Street', 'Cambridge', 'MA', '02140', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"7am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '25 Mystic View Rd', 'Everett', 'MA', '02149', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"7am - 930pm","tuesday":"7am - 930pm","wednesday":"7am - 930pm","thursday":"7am - 930pm","friday":"7am - 930pm","saturday":"7am - 930pm","sunday":"7am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '499 Riverside Ave', 'Medford', 'MA', '02155', NULL, NULL, TRUE, TRUE, TRUE, TRUE, '{"monday":"6am - 930pm","tuesday":"6am - 930pm","wednesday":"6am - 930pm","thursday":"6am - 930pm","friday":"6am - 930pm","saturday":"6am - 930pm","sunday":"6am - 9pm"}'::jsonb, '{"monday":"6am - 930pm","tuesday":"6am - 930pm","wednesday":"6am - 930pm","thursday":"6am - 930pm","friday":"6am - 930pm","saturday":"6am - 930pm","sunday":"6am - 9pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '121 Brookline Ave', 'Boston', 'MA', '02215', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6am - 11pm","tuesday":"6am - 11pm","wednesday":"6am - 11pm","thursday":"6am - 11pm","friday":"6am - 11pm","saturday":"6am - 11pm","sunday":"7am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '115 Stuart Street', 'Boston', 'MA', '02116', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"7am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '200 High Street', 'Boston', 'MA', '02110', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"630am - 9pm","tuesday":"630am - 9pm","wednesday":"630am - 9pm","thursday":"630am - 9pm","friday":"630am - 9pm","saturday":"8am - 8pm","sunday":"8am - 6pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '289 Huntington Avenue', 'Boston', 'MA', '02115', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"7am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '364 Brookline Avenue', 'Boston', 'MA', '02115', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6am - 11pm","tuesday":"6am - 11pm","wednesday":"6am - 11pm","thursday":"6am - 11pm","friday":"6am - 11pm","saturday":"7am - 7pm","sunday":"7am - 7pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '300 Longwood Avenue', 'Boston', 'MA', '02115', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '75 Francis Street', 'Boston', 'MA', '02115', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '8 Allstate Road', 'Dorchester', 'MA', '02125', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"7am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '11 Mount Auburn St', 'Watertown', 'MA', '02472', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"7am - 9pm","tuesday":"7am - 9pm","wednesday":"7am - 9pm","thursday":"7am - 9pm","friday":"7am - 9pm","saturday":"7am - 9pm","sunday":"7am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Panera Bread', 'Panera Bread', '200 Hancock Street', 'Quincy', 'MA', '02171', NULL, NULL, FALSE, TRUE, TRUE, TRUE, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"6am - 930pm"}'::jsonb, '{}'::jsonb );

-- Subway
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '247 Quincy Ave', 'Quincy', 'MA', '02169', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"8am - 9pm","tuesday":"8am - 9pm","wednesday":"8am - 9pm","thursday":"8am - 9pm","friday":"8am - 9pm","saturday":"8am - 9pm","sunday":"8am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '301 Falls Blvd', 'Quincy', 'MA', '02169', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"8am - 11pm","tuesday":"8am - 11pm","wednesday":"8am - 11pm","thursday":"8am - 11pm","friday":"8am - 11pm","saturday":"8am - 11pm","sunday":"8am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '13 William Kelly Square', 'East Boston', 'MA', '02128', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"9am - 10pm","tuesday":"9am - 10pm","wednesday":"9am - 10pm","thursday":"9am - 10pm","friday":"9am - 10pm","saturday":"9am - 10pm","sunday":"9am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '948 Bennington Street', 'East Boston', 'MA', '02128', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"830am - 10pm","tuesday":"830am - 10pm","wednesday":"830am - 10pm","thursday":"830am - 10pm","friday":"830am - 10pm","saturday":"830am - 10pm","sunday":"830am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '207A Centre Street', 'Malden', 'MA', '02148', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"9am - 11pm","tuesday":"9am - 11pm","wednesday":"9am - 11pm","thursday":"9am - 11pm","friday":"9am - 11pm","saturday":"9am - 11pm","sunday":"9am - 8pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '695 Eastern Ave', 'Malden', 'MA', '02148', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"8am - 10pm","tuesday":"8am - 10pm","wednesday":"8am - 10pm","thursday":"8am - 10pm","friday":"8am - 10pm","saturday":"8am - 10pm","sunday":"8am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '2195 Commonwealth Ave', 'Brighton', 'MA', '02135', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"9am - 930pm","tuesday":"9am - 930pm","wednesday":"9am - 930pm","thursday":"9am - 930pm","friday":"9am - 930pm","saturday":"10am - 930pm","sunday":"10am - 930pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '419 Washington Street', 'Brighton', 'MA', '02135', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"9am - 10pm","tuesday":"9am - 10pm","wednesday":"9am - 10pm","thursday":"9am - 10pm","friday":"9am - 10pm","saturday":"9am - 10pm","sunday":"9am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '4 Central Square', 'Cambridge', 'MA', '02139', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"7am - 9pm","tuesday":"7am - 9pm","wednesday":"7am - 9pm","thursday":"7am - 9pm","friday":"7am - 9pm","saturday":"8am - 9pm","sunday":"11am - 8pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', 'Corner of Mt. Auburn &, John F. Kennedy St Level 1, Unit 2-09', 'Cambridge', 'MA', '02138', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"9am - 9pm","tuesday":"9am - 9pm","wednesday":"9am - 9pm","thursday":"9am - 9pm","friday":"9am - 9pm","saturday":"9am - 9pm","sunday":"9am - 9pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '393 Massachusetts Ave Space F-1', 'Boston', 'MA', '02115', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"6am - 130am","tuesday":"6am - 130am","wednesday":"6am - 130am","thursday":"6am - 130am","friday":"6am - 130am","saturday":"8am - 130am","sunday":"9am - 130am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '417 Washington St', 'Boston', 'MA', '02108', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"8am - 6pm","tuesday":"8am - 6pm","wednesday":"8am - 6pm","thursday":"8am - 6pm","friday":"8am - 6pm","saturday":"8am -11pm","sunday":"8am - 6pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '700 Commonwealth Avenue', 'Boston', 'MA', '02215', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"9am - 12am","tuesday":"9am - 12am","wednesday":"9am - 12am","thursday":"9am - 12am","friday":"9am - 12am","saturday":"9am - 12am","sunday":"9am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '904 Huntington Ave', 'Boston', 'MA', '02115', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"8am - 10pm","tuesday":"9am - 10pm","wednesday":"9am - 10pm","thursday":"9am - 10pm","friday":"9am - 10pm","saturday":"9am - 930pm","sunday":"9am - 930pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '981 Tremont St', 'Boston', 'MA', '02116', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"7am - 12am","tuesday":"7am - 12am","wednesday":"7am - 12am","thursday":"7am - 12am","friday":"7am - 12am","saturday":"8am - 12am","sunday":"9am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', 'Ryder Hall Leon Street', 'Boston', 'MA', '02115', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"Closed","tuesday":"Closed","wednesday":"Closed","thursday":"Closed","friday":"Closed","saturday":"Closed","sunday":"Closed"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '1578 Tremont Street Unit 1', 'Boston', 'MA', '02120', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"9am - 10pm","tuesday":"9am - 10pm","wednesday":"9am - 10pm","thursday":"9am - 10pm","friday":"9am - 10pm","saturday":"9am - 10pm","sunday":"9am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '230 Tremont St', 'Boston', 'MA', '02116', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"Closed","tuesday":"Closed","wednesday":"Closed","thursday":"Closed","friday":"Closed","saturday":"Closed","sunday":"Closed"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '274 Franklin St', 'Boston', 'MA', '02110', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"Closed","tuesday":"Closed","wednesday":"Closed","thursday":"Closed","friday":"Closed","saturday":"Closed","sunday":"Closed"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '350 Longwood Ave', 'Boston', 'MA', '02115', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"7am - 9pm","tuesday":"7am - 9pm","wednesday":"7am - 9pm","thursday":"7am - 9pm","friday":"7am - 9pm","saturday":"10am - 8pm","sunday":"10am - 8pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '3 Everett Street Unit 3D-2', 'Revere', 'MA', '02151', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"830am - 1130pm","tuesday":"830am - 1130pm","wednesday":"830am - 1130pm","thursday":"830am - 1130pm","friday":"830am - 1130pm","saturday":"830am - 1130pm","sunday":"10am - 1130pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '339 Squire Road', 'Revere', 'MA', '02151', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"8am - 12am","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"12am - 1130pm","sunday":"12am - 1130pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '11 West Broadway Unit 03', 'South Boston', 'MA', '02127', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"Closed","tuesday":"Closed","wednesday":"Closed","thursday":"Closed","friday":"Closed","saturday":"Closed","sunday":"Closed"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '711-723 Sommerville Ave', 'Sommerville', 'MA', '02143', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"7am - 10pm","tuesday":"7am - 10pm","wednesday":"7am - 10pm","thursday":"7am - 10pm","friday":"7am - 10pm","saturday":"8am - 10pm","sunday":"8am - 10pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'Subway', 'Subway', '860 Broadway', 'Somerville', 'MA', '02144', NULL, NULL, FALSE, FALSE, TRUE, TRUE, '{"monday":"9am - 10pm","tuesday":"9am - 10pm","wednesday":"9am - 10pm","thursday":"9am - 10pm","friday":"9am - 10pm","saturday":"9am - 10pm","sunday":"9am - 10pm"}'::jsonb, '{}'::jsonb );

-- McDonald's

INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '14 Mcgrath Hwy', 'Sommerville', 'MA', '02143', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"5am - 11pm","tuesday":"5am - 11pm","wednesday":"5am - 11pm","thursday":"5am - 11pm","friday":"5am - 11pm","saturday":"5am - 11pm","sunday":"5am - 11pm"}'::jsonb, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '463 Massachusetts Ave', 'Cambridge', 'MA', '02139', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"430am - 4am","tuesday":"430am - 4am","wednesday":"430am - 4am","thursday":"430am - 4am","friday":"430am - 4am","saturday":"430am - 4am","sunday":"430am - 4am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '186 Ale Wife Brook Pky', 'Cambridge', 'MA', '02138', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"7am - 2am","tuesday":"7am - 2am","wednesday":"7am - 2am","thursday":"7am - 2am","friday":"7am - 2am","saturday":"7am - 2am","sunday":"7am - 2am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '100 Legends Way', 'Boston', 'MA', '02114', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"7am - 12am","tuesday":"7am - 12am","wednesday":"7am - 12am","thursday":"7am - 12am","friday":"7am - 12am","saturday":"7am - 12am","sunday":"7am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '128 Broadway', 'Everett', 'MA', '02149', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '540 Commonwealth Ave', 'Boston', 'MA', '02215', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"6am - 2am","tuesday":"6am - 2am","wednesday":"6am - 2am","thursday":"6am - 2am","friday":"6am - 2am","saturday":"6am - 2am","sunday":"6am - 2am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '146 Tremont St', 'Boston', 'MA', '02111', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"7am - 12am","tuesday":"7am - 12am","wednesday":"7am - 12am","thursday":"7am - 12am","friday":"7am - 12am","saturday":"7am - 12am","sunday":"7am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '1223 Commonwealth Ave', 'Allston', 'MA', '02134', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"6am - 3am","tuesday":"6am - 3am","wednesday":"6am - 3am","thursday":"6am - 3am","friday":"6am - 3am","saturday":"6am - 3am","sunday":"6am - 3am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '329 Washington St', 'Boston', 'MA', '02108', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"6am - 1130pm","tuesday":"6am - 1130pm","wednesday":"6am - 1130pm","thursday":"6am - 1130pm","friday":"6am - 1130pm","saturday":"6am - 1130pm","sunday":"7am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '350 Longwood Ave (Longwood Galleria)', 'Boston', 'MA', '02115', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"630am - 10pm","tuesday":"630am - 10pm","wednesday":"630am - 10pm","thursday":"630am - 10pm","friday":"630am - 10pm","saturday":"7am - 8pm","sunday":"730am - 8pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '2 South Station (Train Station)', 'Boston', 'MA', '02110', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"5am - 12am","tuesday":"5am - 12am","wednesday":"5am - 12am","thursday":"5am - 12am","friday":"5am - 12am","saturday":"5am - 12am","sunday":"5am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '178 Border St', 'East Boston', 'MA', '02128', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 10pm","tuesday":"6am - 4am","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb, '{"monday":"6am - 10pm","tuesday":"6am - 4am","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"4am - 10pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '178 Border St', 'East Boston', 'MA', '02128', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 10pm","tuesday":"6am - 4am","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"4am - 10pm"}'::jsonb, '{"monday":"6am - 10pm","tuesday":"6am - 4am","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"4am - 10pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '700 Atlantic Ave', 'Boston', 'MA', '02110', NULL, NULL, FALSE, FALSE, TRUE, FALSE, '{"monday":"5am - 12am","tuesday":"5am - 12am","wednesday":"5am - 12am","thursday":"5am - 12am","friday":"5am - 12am","saturday":"5am - 12am","sunday":"5am - 12am"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '360 Western Ave', 'Brighton', 'MA', '02135', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"5am - 11pm","tuesday":"5am - 11pm","wednesday":"5am - 11pm","thursday":"5am - 11pm","friday":"5am - 11pm","saturday":"5am - 11pm","sunday":"5am - 11pm"}'::jsonb, '{"monday":"5am - 3am","tuesday":"5am - 3am","wednesday":"5am - 3am","thursday":"5am - 3am","friday":"5am - 3am","saturday":"5am - 3am","sunday":"5am - 3am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '1750 Soldiers Fld Rd', 'Brighton', 'MA', '02135', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '472 Broadway', 'Chelsea', 'MA', '02150', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"6am - 11pm","tuesday":"6am - 11pm","wednesday":"6am - 11pm","thursday":"6am - 11pm","friday":"6am - 11pm","saturday":"6am - 11pm","sunday":"6am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '870 Massachusetts Ave', 'Boston', 'MA', '02118', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"7am - 10pm","tuesday":"7am - 10pm","wednesday":"7am - 10pm","thursday":"7am - 10pm","friday":"7am - 10pm","saturday":"7am - 10pm","sunday":"7am - 10pm"}'::jsonb, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '1018 Revere Beach Pkwy', 'Chelsea', 'MA', '02150', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 11pm","tuesday":"6am - 11pm","wednesday":"6am - 11pm","thursday":"6am - 11pm","friday":"6am - 11pm","saturday":"6am - 11pm","sunday":"6am - 11pm"}'::jsonb, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '301 Warren St', 'Roxbury', 'MA', '02119', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 9pm","tuesday":"6am - 9pm","wednesday":"6am - 9pm","thursday":"6am - 9pm","friday":"6am - 9pm","saturday":"6am - 9pm","sunday":"6am - 9pm"}'::jsonb, '{"monday":"6am - 1am","tuesday":"6am - 1am","wednesday":"6am - 1am","thursday":"6am - 1am","friday":"6am - 1am","saturday":"6am - 1am","sunday":"6am - 1am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '114 Broadway', 'Malden', 'MA', '02148', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"5am - 1am","tuesday":"5am - 1am","wednesday":"5am - 1am","thursday":"5am - 1am","friday":"5am - 1am","saturday":"5am - 1am","sunday":"5am - 1am"}'::jsonb, '{"monday":"5am - 1am","tuesday":"5am - 1am","wednesday":"5am - 1am","thursday":"5am - 1am","friday":"5am - 1am","saturday":"5am - 1am","sunday":"5am - 1am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '170 Revere Beach Pky', 'Chelsea', 'MA', '02150', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"6am - 10pm"}'::jsonb, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"6am - 10pm"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '3064 Washington St', 'Roxbury', 'MA', '02119', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"6am - 10pm","tuesday":"6am - 10pm","wednesday":"6am - 10pm","thursday":"6am - 10pm","friday":"6am - 10pm","saturday":"6am - 10pm","sunday":"6am - 10pm"}'::jsonb, '{"monday":"6am - 12am","tuesday":"6am - 12am","wednesday":"6am - 12am","thursday":"6am - 12am","friday":"6am - 12am","saturday":"6am - 12am","sunday":"7am - 12am"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '473 Southern Artery', 'Quincy', 'MA', '02169', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '275 Hancock St', 'Quincy', 'MA', '02171', NULL, NULL, TRUE, TRUE, TRUE, FALSE, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb, '{"monday":"Open 24 hours","tuesday":"Open 24 hours","wednesday":"Open 24 hours","thursday":"Open 24 hours","friday":"Open 24 hours","saturday":"Open 24 hours","sunday":"Open 24 hours"}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '515 Gallivan Blvd', 'Dorchester', 'MA', '02124', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"6am - 11pm","tuesday":"6am - 11pm","wednesday":"6am - 11pm","thursday":"6am - 11pm","friday":"6am - 11pm","saturday":"6am - 11pm","sunday":"6am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '1513 Dorchester Ave', 'Dorchester', 'MA', '02122', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"6am - 11pm","tuesday":"6am - 11pm","wednesday":"6am - 11pm","thursday":"6am - 11pm","friday":"6am - 11pm","saturday":"6am - 11pm","sunday":"6am - 11pm"}'::jsonb, '{}'::jsonb );
INSERT INTO restaurant_locations ( name, company_id, address, city, state, zip, latitude, longitude, has_drive_thru, has_wifi, has_online_ordering, has_catering, dine_in_hours, drive_thru_hours ) VALUES ( 'McDonald''s', 'McDonald''s', '605 Washington St', 'Dorchester', 'MA', '02124', NULL, NULL, FALSE, TRUE, TRUE, FALSE, '{"monday":"6am - 12am","tuesday":"6am - 12am","wednesday":"6am - 12am","thursday":"6am - 12am","friday":"6am - 12am","saturday":"6am - 12am","sunday":"6am - 12am"}'::jsonb, '{}'::jsonb );






